/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Errors11 } from '../models/errors11';

/**
 * Creates an instance of ComponentsPricePointsSegmentsIdJson422
 */
interface ComponentsPricePointsSegmentsIdJson422 {
  errors?: Errors11;
}

export class ComponentsPricePointsSegmentsIdJson422Error extends ApiError<ComponentsPricePointsSegmentsIdJson422> {}
