/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Errors13 } from '../models/errors13';

/**
 * Creates an instance of ComponentsPricePointsSegmentsBulkJson422Error2
 */
interface ComponentsPricePointsSegmentsBulkJson422Error2 {
  errors: Errors13;
}

export class ComponentsPricePointsSegmentsBulkJson422Error2Error extends ApiError<ComponentsPricePointsSegmentsBulkJson422Error2> {}
