/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Errors10 } from '../models/errors10';

/**
 * Creates an instance of ComponentsPricePointsSegmentsJson422Error2
 */
interface ComponentsPricePointsSegmentsJson422Error2 {
  errors?: Errors10;
}

export class ComponentsPricePointsSegmentsJson422Error2Error extends ApiError<ComponentsPricePointsSegmentsJson422Error2> {}
