/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Errors12 } from '../models/errors12';

/**
 * Creates an instance of ComponentsPricePointsSegmentsBulkJson422
 */
interface ComponentsPricePointsSegmentsBulkJson422 {
  errors: Errors12;
}

export class ComponentsPricePointsSegmentsBulkJson422Error extends ApiError<ComponentsPricePointsSegmentsBulkJson422> {}
