/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Errors9 } from '../models/errors9';

/**
 * Creates an instance of ComponentsPricePointsSegmentsJson422
 */
interface ComponentsPricePointsSegmentsJson422 {
  errors?: Errors9;
}

export class ComponentsPricePointsSegmentsJson422Error extends ApiError<ComponentsPricePointsSegmentsJson422> {}
