/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of CouponsValidateJson404
 */
interface CouponsValidateJson404 {
  errors?: string;
}

export class CouponsValidateJson404Error extends ApiError<CouponsValidateJson404> {}
