/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Errors6 } from '../models/errors6';

/**
 * Creates an instance of OffersJson422
 */
interface OffersJson422 {
  errors?: Errors6;
}

export class OffersJson422Error extends ApiError<OffersJson422> {}
