/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Errors } from '../models/errors';

/**
 * Creates an instance of PortalCustomersManagementLinkJson429
 */
interface PortalCustomersManagementLinkJson429 {
  errors?: Errors;
}

export class PortalCustomersManagementLinkJson429Error extends ApiError<PortalCustomersManagementLinkJson429> {}
