/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Errors1 } from '../models/errors1';

/**
 * Creates an instance of ProductPricePointsCurrencyPricesJson422
 */
interface ProductPricePointsCurrencyPricesJson422 {
  errors?: Errors1;
}

export class ProductPricePointsCurrencyPricesJson422Error extends ApiError<ProductPricePointsCurrencyPricesJson422> {}
