/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of ReferralCodesValidateJson404
 */
interface ReferralCodesValidateJson404 {
  errors?: string;
}

export class ReferralCodesValidateJson404Error extends ApiError<ReferralCodesValidateJson404> {}
