/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Errors15 } from '../models/errors15';

/**
 * Creates an instance of SubscriptionsPrepaymentsRefundsJson400
 */
interface SubscriptionsPrepaymentsRefundsJson400 {
  errors?: Errors15;
}

export class SubscriptionsPrepaymentsRefundsJson400Error extends ApiError<SubscriptionsPrepaymentsRefundsJson400> {}
