/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of SubscriptionsInvoicesJson422
 */
interface SubscriptionsInvoicesJson422 {
  errors?: unknown;
}

export class SubscriptionsInvoicesJson422Error extends ApiError<SubscriptionsInvoicesJson422> {}
