/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of SubscriptionsRemoveCouponJson422
 */
interface SubscriptionsRemoveCouponJson422 {
  subscription?: string[];
}

export class SubscriptionsRemoveCouponJson422Error extends ApiError<SubscriptionsRemoveCouponJson422> {}
