/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Errors3 } from '../models/errors3';

/**
 * Creates an instance of SubscriptionsAllocationsPreviewJson422
 */
interface SubscriptionsAllocationsPreviewJson422 {
  errors?: Errors3[];
}

export class SubscriptionsAllocationsPreviewJson422Error extends ApiError<SubscriptionsAllocationsPreviewJson422> {}
