/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Errors14 } from '../models/errors14';

/**
 * Creates an instance of SubscriptionsMrrJson400
 */
interface SubscriptionsMrrJson400 {
  errors: Errors14;
}

export class SubscriptionsMrrJson400Error extends ApiError<SubscriptionsMrrJson400> {}
