/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Errors2 } from '../models/errors2';

/**
 * Creates an instance of SubscriptionsPricePointsJson422
 */
interface SubscriptionsPricePointsJson422 {
  errors?: Errors2[];
}

export class SubscriptionsPricePointsJson422Error extends ApiError<SubscriptionsPricePointsJson422> {}
