/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Errors8 } from '../models/errors8';

/**
 * Creates an instance of SubscriptionGroupsJson422Error2
 */
interface SubscriptionGroupsJson422Error2 {
  errors?: Errors8;
}

export class SubscriptionGroupsJson422Error2Error extends ApiError<SubscriptionGroupsJson422Error2> {}
