/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Errors1 } from '../models/errors1';

/**
 * Creates an instance of SubscriptionsActivateJson400
 */
interface SubscriptionsActivateJson400 {
  errors?: Errors1;
}

export class SubscriptionsActivateJson400Error extends ApiError<SubscriptionsActivateJson400> {}
