/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of SubscriptionsRetryJson422
 */
interface SubscriptionsRetryJson422 {
  errors?: unknown[];
}

export class SubscriptionsRetryJson422Error extends ApiError<SubscriptionsRetryJson422> {}
