/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Errors18 } from '../models/errors18';

/**
 * Creates an instance of SubscriptionsProformaInvoicesPreviewJson400
 */
interface SubscriptionsProformaInvoicesPreviewJson400 {
  errors?: Errors18;
}

export class SubscriptionsProformaInvoicesPreviewJson400Error extends ApiError<SubscriptionsProformaInvoicesPreviewJson400> {}
