/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of SubscriptionGroupsJson422
 */
interface SubscriptionGroupsJson422 {
  errors?: string;
}

export class SubscriptionGroupsJson422Error extends ApiError<SubscriptionGroupsJson422> {}
