/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Errors7 } from '../models/errors7';

/**
 * Creates an instance of SubscriptionGroupsSignupJson422
 */
interface SubscriptionGroupsSignupJson422 {
  errors: Errors7;
}

export class SubscriptionGroupsSignupJson422Error extends ApiError<SubscriptionGroupsSignupJson422> {}
