/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Errors16 } from '../models/errors16';

/**
 * Creates an instance of SubscriptionsPrepaymentsRefundsJson422
 */
interface SubscriptionsPrepaymentsRefundsJson422 {
  errors?: Errors16;
}

export class SubscriptionsPrepaymentsRefundsJson422Error extends ApiError<SubscriptionsPrepaymentsRefundsJson422> {}
