/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Errors4 } from '../models/errors4';

/**
 * Creates an instance of SubscriptionsComponentsAllocationsAllocationIdJson422
 */
interface SubscriptionsComponentsAllocationsAllocationIdJson422 {
  errors?: Errors4[];
}

export class SubscriptionsComponentsAllocationsAllocationIdJson422Error extends ApiError<SubscriptionsComponentsAllocationsAllocationIdJson422> {}
