/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, oneOf, Schema } from '../../schema';

/** This is a container type for one-of types. */
export type AllocationPreviewItemQuantity = number;

export const allocationPreviewItemQuantitySchema: Schema<AllocationPreviewItemQuantity> = oneOf(
  [number()]
);

export namespace AllocationPreviewItemQuantity {
  /**
  * Validation method to narrow down union type to number type case.
  *
  * This is Precision case.
  */
  export function isNumber(value: unknown): value is number {
    return typeof value === 'number';
  }
}
