/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, dict, oneOf, Schema } from '../../schema';

/** This is a container type for one-of types. */
export type CreateOrUpdateCouponRestrictedComponents = Record<string, boolean>;

export const createOrUpdateCouponRestrictedComponentsSchema: Schema<CreateOrUpdateCouponRestrictedComponents> = oneOf(
  [dict(boolean())]
);

export namespace CreateOrUpdateCouponRestrictedComponents {
  /**
  * Validation method to narrow down union type to Record<string, boolean> type case.
  *
  * This is Map of Boolean case.
  */
  export function isMapOfBoolean(value: unknown): value is Record<string, boolean> {
    return typeof value === 'object' && value !== null && Object.values(value).every((val) => typeof val === 'boolean');
  }
}
