/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { oneOf, Schema, validateAndMap } from '../../schema';
import { EventData, eventDataSchema } from '../eventData';

/** This is a container type for one-of types. */
export type EventEventSpecificData = EventData;

export const eventEventSpecificDataSchema: Schema<EventEventSpecificData> = oneOf(
  [eventDataSchema]
);

export namespace EventEventSpecificData {
  /**
  * Validation method to narrow down union type to EventData type case.
  *
  * This is Event Data case.
  */
  export function isEventData(value: unknown): value is EventData {
    const validationResult = validateAndMap(value, eventDataSchema);
    return validationResult.errors === false;
  }
}
