/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { anyOf, Schema, validateAndMap } from '../../schema';
import {
  ApplyPaymentEventData,
  applyPaymentEventDataSchema,
} from '../applyPaymentEventData';

/** This is a container type for any-of types. */
export type InvoiceEventEventData = ApplyPaymentEventData;

export const invoiceEventEventDataSchema: Schema<InvoiceEventEventData> = anyOf(
  [applyPaymentEventDataSchema]
);

export namespace InvoiceEventEventData {
  /**
  * Validation method to narrow down union type to ApplyPaymentEventData type case.
  *
  * This is Apply Payment Event Data case.
  */
  export function isApplyPaymentEventData(value: unknown): value is ApplyPaymentEventData {
    const validationResult = validateAndMap(value, applyPaymentEventDataSchema);
    return validationResult.errors === false;
  }
}
