/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { oneOf, Schema, validateAndMap } from '../../schema';
import {
  ExtendedIntervalUnitEnum,
  extendedIntervalUnitEnumSchema,
} from '../extendedIntervalUnitEnum';

/** This is a container type for one-of types. */
export type ProductExpirationIntervalUnitCase0 = ExtendedIntervalUnitEnum;

export const productExpirationIntervalUnitCase0Schema: Schema<ProductExpirationIntervalUnitCase0> = oneOf(
  [extendedIntervalUnitEnumSchema]
);

export namespace ProductExpirationIntervalUnitCase0 {
  /**
  * Validation method to narrow down union type to ExtendedIntervalUnitEnum type case.
  *
  * This is Extended Interval Unit case.
  */
  export function isExtendedIntervalUnitEnum(value: unknown): value is ExtendedIntervalUnitEnum {
    const validationResult = validateAndMap(value, extendedIntervalUnitEnumSchema);
    return validationResult.errors === false;
  }
}
