/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { oneOf, Schema, validateAndMap } from '../../schema';
import { IntervalUnitEnum, intervalUnitEnumSchema } from '../intervalUnitEnum';

/** This is a container type for one-of types. */
export type ProductIntervalUnit = IntervalUnitEnum;

export const productIntervalUnitSchema: Schema<ProductIntervalUnit> = oneOf([
  intervalUnitEnumSchema,
]);

export namespace ProductIntervalUnit {
  /**
  * Validation method to narrow down union type to IntervalUnitEnum type case.
  *
  * This is Interval Unit case.
  */
  export function isIntervalUnitEnum(value: unknown): value is IntervalUnitEnum {
    const validationResult = validateAndMap(value, intervalUnitEnumSchema);
    return validationResult.errors === false;
  }
}
