/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { oneOf, Schema, validateAndMap } from '../../schema';
import {
  PaymentCollectionMethodForSubscriptionEnum,
  paymentCollectionMethodForSubscriptionEnumSchema,
} from '../paymentCollectionMethodForSubscriptionEnum';

/** This is a container type for one-of types. */
export type SubscriptionPaymentCollectionMethod = PaymentCollectionMethodForSubscriptionEnum;

export const subscriptionPaymentCollectionMethodSchema: Schema<SubscriptionPaymentCollectionMethod> = oneOf(
  [paymentCollectionMethodForSubscriptionEnumSchema]
);

export namespace SubscriptionPaymentCollectionMethod {
  /**
  * Validation method to narrow down union type to PaymentCollectionMethodForSubscriptionEnum type case.
  *
  * This is Payment Collection Method for Subscription case.
  */
  export function isPaymentCollectionMethodForSubscriptionEnum(value: unknown): value is PaymentCollectionMethodForSubscriptionEnum {
    const validationResult = validateAndMap(value, paymentCollectionMethodForSubscriptionEnumSchema);
    return validationResult.errors === false;
  }
}
