/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { oneOf, Schema, validateAndMap } from '../../schema';
import {
  PricePointTypeEnum,
  pricePointTypeEnumSchema,
} from '../pricePointTypeEnum';

/** This is a container type for one-of types. */
export type SubscriptionComponentPricePointType = PricePointTypeEnum;

export const subscriptionComponentPricePointTypeSchema: Schema<SubscriptionComponentPricePointType> = oneOf(
  [pricePointTypeEnumSchema]
);

export namespace SubscriptionComponentPricePointType {
  /**
  * Validation method to narrow down union type to PricePointTypeEnum type case.
  *
  * This is Price Point Type case.
  */
  export function isPricePointTypeEnum(value: unknown): value is PricePointTypeEnum {
    const validationResult = validateAndMap(value, pricePointTypeEnumSchema);
    return validationResult.errors === false;
  }
}
