/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { oneOf, Schema, validateAndMap } from '../../schema';
import {
  CancellationMethodEnum,
  cancellationMethodEnumSchema,
} from '../cancellationMethodEnum';

/** This is a container type for one-of types. */
export type SubscriptionCancellationMethod = CancellationMethodEnum;

export const subscriptionCancellationMethodSchema: Schema<SubscriptionCancellationMethod> = oneOf(
  [cancellationMethodEnumSchema]
);

export namespace SubscriptionCancellationMethod {
  /**
  * Validation method to narrow down union type to CancellationMethodEnum type case.
  *
  * This is Cancellation Method case.
  */
  export function isCancellationMethodEnum(value: unknown): value is CancellationMethodEnum {
    const validationResult = validateAndMap(value, cancellationMethodEnumSchema);
    return validationResult.errors === false;
  }
}
