/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, oneOf, Schema, validateAndMap } from '../../schema';
import { SnapDayEnum, snapDayEnumSchema } from '../snapDayEnum';

/** This is a container type for one-of types. */
export type UpdateSubscriptionSnapDay = SnapDayEnum | number;

export const updateSubscriptionSnapDaySchema: Schema<UpdateSubscriptionSnapDay> = oneOf(
  [snapDayEnumSchema, number()]
);

export namespace UpdateSubscriptionSnapDay {
  /**
  * Validation method to narrow down union type to SnapDayEnum type case.
  *
  * This is SnapDay case.
  */
  export function isSnapDayEnum(value: unknown): value is SnapDayEnum {
    const validationResult = validateAndMap(value, snapDayEnumSchema);
    return validationResult.errors === false;
  }

  /**
  * Validation method to narrow down union type to number type case.
  *
  * This is Number case.
  */
  export function isNumber(value: unknown): value is number {
    return typeof value === 'number';
  }
}
