/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface AllocationExpirationDate {
  expiresAt?: string;
}

export const allocationExpirationDateSchema: Schema<AllocationExpirationDate> = object(
  { expiresAt: ['expires_at', optional(string())] }
);
