/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, numberEnum } from '../schema';

/**
 * Enum for AutoInviteEnum
 */
export enum AutoInviteEnum {
  No = 0,
  Yes = 1,
}

/**
 * Schema for AutoInviteEnum
 */
export const autoInviteEnumSchema: Schema<AutoInviteEnum> = numberEnum(AutoInviteEnum);
