/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for BankAccountVaultEnum
 */
export enum BankAccountVaultEnum {
  Authorizenet = 'authorizenet',
  Stripe = 'stripe',
}

/**
 * Schema for BankAccountVaultEnum
 */
export const bankAccountVaultEnumSchema: Schema<BankAccountVaultEnum> = stringEnum(BankAccountVaultEnum);
