/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for BankAccountTypeEnum
 */
export enum BankAccountTypeEnum {
  Checking = 'checking',
  Savings = 'savings',
}

/**
 * Schema for BankAccountTypeEnum
 */
export const bankAccountTypeEnumSchema: Schema<BankAccountTypeEnum> = stringEnum(BankAccountTypeEnum);
