/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for BasicDateFieldEnum
 */
export enum BasicDateFieldEnum {
  UpdatedAt = 'updated_at',
  CreatedAt = 'created_at',
}

/**
 * Schema for BasicDateFieldEnum
 */
export const basicDateFieldEnumSchema: Schema<BasicDateFieldEnum> = stringEnum(BasicDateFieldEnum);
