/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CancellationMethodEnum
 */
export enum CancellationMethodEnum {
  MerchantUi = 'merchant_ui',
  MerchantApi = 'merchant_api',
  Dunning = 'dunning',
  BillingPortal = 'billing_portal',
}

/**
 * Schema for CancellationMethodEnum
 */
export const cancellationMethodEnumSchema: Schema<CancellationMethodEnum> = stringEnum(CancellationMethodEnum);
