/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CardTypeEnum
 */
export enum CardTypeEnum {
  Bogus = 'bogus',
  Visa = 'visa',
  Master = 'master',
  Discover = 'discover',
  AmericanExpress = 'american_express',
  DinersClub = 'diners_club',
  Jcb = 'jcb',
  Switch = 'switch',
  Solo = 'solo',
  Dankort = 'dankort',
  Maestro = 'maestro',
  Laser = 'laser',
  Forbrugsforeningen = 'forbrugsforeningen',
}

/**
 * Schema for CardTypeEnum
 */
export const cardTypeEnumSchema: Schema<CardTypeEnum> = stringEnum(CardTypeEnum);
