/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ComponentKindPathEnum
 */
export enum ComponentKindPathEnum {
  MeteredComponents = 'metered_components',
  QuantityBasedComponents = 'quantity_based_components',
  OnOffComponents = 'on_off_components',
  PrepaidUsageComponents = 'prepaid_usage_components',
  EventBasedComponents = 'event_based_components',
}

/**
 * Schema for ComponentKindPathEnum
 */
export const componentKindPathEnumSchema: Schema<ComponentKindPathEnum> = stringEnum(ComponentKindPathEnum);
