/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CompoundingStrategyEnum
 */
export enum CompoundingStrategyEnum {
  Compound = 'compound',
  Fullprice = 'full-price',
}

/**
 * Schema for CompoundingStrategyEnum
 */
export const compoundingStrategyEnumSchema: Schema<CompoundingStrategyEnum> = stringEnum(CompoundingStrategyEnum);
