/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ComponentKindEnum
 */
export enum ComponentKindEnum {
  MeteredComponent = 'metered_component',
  QuantityBasedComponent = 'quantity_based_component',
  OnOffComponent = 'on_off_component',
  PrepaidUsageComponent = 'prepaid_usage_component',
  EventBasedComponent = 'event_based_component',
}

/**
 * Schema for ComponentKindEnum
 */
export const componentKindEnumSchema: Schema<ComponentKindEnum> = stringEnum(ComponentKindEnum);
