/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import {
  CreateComponentPrice,
  createComponentPriceSchema,
} from './createComponentPrice';

export interface ComponentPricePointItem {
  name?: string;
  handle?: string;
  pricingScheme?: string;
  prices?: CreateComponentPrice[];
}

export const componentPricePointItemSchema: Schema<ComponentPricePointItem> = object(
  {
    name: ['name', optional(string())],
    handle: ['handle', optional(string())],
    pricingScheme: ['pricing_scheme', optional(string())],
    prices: ['prices', optional(array(lazy(() => createComponentPriceSchema)))],
  }
);
