/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, number, object, optional, Schema, string } from '../schema';
import {
  RestrictionTypeEnum,
  restrictionTypeEnumSchema,
} from './restrictionTypeEnum';

export interface CouponRestriction {
  id?: string;
  itemType?: RestrictionTypeEnum;
  itemId?: number;
  name?: string;
  handle?: string | null;
}

export const couponRestrictionSchema: Schema<CouponRestriction> = object({
  id: ['id', optional(string())],
  itemType: ['item_type', optional(restrictionTypeEnumSchema)],
  itemId: ['item_id', optional(number())],
  name: ['name', optional(string())],
  handle: ['handle', optional(nullable(string()))],
});
