/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { CreatedPrepayment, createdPrepaymentSchema } from './createdPrepayment';

export interface CreatePrepaymentResponse {
  prepayment: CreatedPrepayment;
}

export const createPrepaymentResponseSchema: Schema<CreatePrepaymentResponse> = object(
  { prepayment: ['prepayment', lazy(() => createdPrepaymentSchema)] }
);
