/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CreatePaymentProfileVaultEnum
 */
export enum CreatePaymentProfileVaultEnum {
  Bogus = 'bogus',
  Authorizenet = 'authorizenet',
  AuthorizenetCim = 'authorizenet_cim',
  Beanstream = 'beanstream',
  BraintreeBlue = 'braintree_blue',
  Cybersource = 'cybersource',
  Elavon = 'elavon',
  Eway = 'eway',
  EwayRapidStd = 'eway_rapid_std',
  Firstdata = 'firstdata',
  Forte = 'forte',
  Gocardless = 'gocardless',
  Litle = 'litle',
  Moneris = 'moneris',
  Orbital = 'orbital',
  PaymentExpress = 'payment_express',
  Paymill = 'paymill',
  Pin = 'pin',
  Square = 'square',
  StripeConnect = 'stripe_connect',
  TrustCommerce = 'trust_commerce',
  Wirecard = 'wirecard',
  Checkout = 'checkout',
}

/**
 * Schema for CreatePaymentProfileVaultEnum
 */
export const createPaymentProfileVaultEnumSchema: Schema<CreatePaymentProfileVaultEnum> = stringEnum(CreatePaymentProfileVaultEnum);
