/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';
import {
  CreateComponentPriceUnitPrice,
  createComponentPriceUnitPriceSchema,
} from './containers/createComponentPriceUnitPrice';

export interface CreateComponentPrice {
  startingQuantity?: number;
  /** The price can contain up to 8 decimal places. i.e. 1.00 or 0.0012 or 0.00000065 */
  unitPrice?: CreateComponentPriceUnitPrice;
}

export const createComponentPriceSchema: Schema<CreateComponentPrice> = object({
  startingQuantity: ['starting_quantity', optional(number())],
  unitPrice: ['unit_price', optional(createComponentPriceUnitPriceSchema)],
});
