/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  CreateInvoicePayment,
  createInvoicePaymentSchema,
} from './createInvoicePayment';
import {
  InvoicePaymentTypeEnum,
  invoicePaymentTypeEnumSchema,
} from './invoicePaymentTypeEnum';

export interface CreateInvoicePaymentRequest {
  payment: CreateInvoicePayment;
  /** The type of payment to be applied to an Invoice. */
  type?: InvoicePaymentTypeEnum;
}

export const createInvoicePaymentRequestSchema: Schema<CreateInvoicePaymentRequest> = object(
  {
    payment: ['payment', lazy(() => createInvoicePaymentSchema)],
    type: ['type', optional(invoicePaymentTypeEnumSchema)],
  }
);
