/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { dict, object, optional, Schema } from '../schema';
import {
  CreateOrUpdateCouponCoupon,
  createOrUpdateCouponCouponSchema,
} from './containers/createOrUpdateCouponCoupon';
import {
  CreateOrUpdateCouponRestrictedComponents,
  createOrUpdateCouponRestrictedComponentsSchema,
} from './containers/createOrUpdateCouponRestrictedComponents';
import {
  CreateOrUpdateCouponRestrictedProducts,
  createOrUpdateCouponRestrictedProductsSchema,
} from './containers/createOrUpdateCouponRestrictedProducts';

export interface CreateOrUpdateCoupon {
  coupon?: CreateOrUpdateCouponCoupon;
  /** An object where the keys are product_ids and the values are booleans indicating if the coupon should be applicable to the product */
  restrictedProducts?: Record<string, CreateOrUpdateCouponRestrictedProducts>;
  /** An object where the keys are component_ids and the values are booleans indicating if the coupon should be applicable to the component */
  restrictedComponents?: Record<string, CreateOrUpdateCouponRestrictedComponents>;
}

export const createOrUpdateCouponSchema: Schema<CreateOrUpdateCoupon> = object({
  coupon: ['coupon', optional(createOrUpdateCouponCouponSchema)],
  restrictedProducts: [
    'restricted_products',
    optional(dict(createOrUpdateCouponRestrictedProductsSchema)),
  ],
  restrictedComponents: [
    'restricted_components',
    optional(dict(createOrUpdateCouponRestrictedComponentsSchema)),
  ],
});
