/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import {
  CreateMultiInvoicePaymentAmount,
  createMultiInvoicePaymentAmountSchema,
} from './containers/createMultiInvoicePaymentAmount';
import {
  CreateInvoicePaymentApplication,
  createInvoicePaymentApplicationSchema,
} from './createInvoicePaymentApplication';
import {
  InvoicePaymentMethodTypeEnum,
  invoicePaymentMethodTypeEnumSchema,
} from './invoicePaymentMethodTypeEnum';

export interface CreateMultiInvoicePayment {
  /** A description to be attached to the payment. */
  memo?: string;
  /** Additional information related to the payment method (eg. Check #). */
  details?: string;
  /** The type of payment method used. */
  method?: InvoicePaymentMethodTypeEnum;
  /** Dollar amount of the sum of the invoices payment (eg. "10.50" => $10.50). */
  amount: CreateMultiInvoicePaymentAmount;
  /** Date reflecting when the payment was received from a customer. Must be in the past. */
  receivedOn?: string;
  applications: CreateInvoicePaymentApplication[];
}

export const createMultiInvoicePaymentSchema: Schema<CreateMultiInvoicePayment> = object(
  {
    memo: ['memo', optional(string())],
    details: ['details', optional(string())],
    method: ['method', optional(invoicePaymentMethodTypeEnumSchema)],
    amount: ['amount', optional(createMultiInvoicePaymentAmountSchema)],
    receivedOn: ['received_on', optional(string())],
    applications: [
      'applications',
      array(lazy(() => createInvoicePaymentApplicationSchema)),
    ],
  }
);
