/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';
import {
  CurrencyPriceRoleEnum,
  currencyPriceRoleEnumSchema,
} from './currencyPriceRoleEnum';

export interface CreateProductCurrencyPrice {
  /** ISO code for one of the site level currencies. */
  currency: string;
  /** Price for the given role. */
  price: number;
  /** Role for the price. */
  role: CurrencyPriceRoleEnum;
}

export const createProductCurrencyPriceSchema: Schema<CreateProductCurrencyPrice> = object(
  {
    currency: ['currency', string()],
    price: ['price', number()],
    role: ['role', currencyPriceRoleEnumSchema],
  }
);
