/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import {
  CreateUsageQuantity,
  createUsageQuantitySchema,
} from './containers/createUsageQuantity';

export interface CreateUsage {
  /** integer by default or decimal number if fractional quantities are enabled for the component */
  quantity?: CreateUsageQuantity;
  pricePointId?: string;
  memo?: string;
}

export const createUsageSchema: Schema<CreateUsage> = object({
  quantity: ['quantity', optional(createUsageQuantitySchema)],
  pricePointId: ['price_point_id', optional(string())],
  memo: ['memo', optional(string())],
});
