/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import {
  CreateMetafieldsRequestMetafields,
  createMetafieldsRequestMetafieldsSchema,
} from './containers/createMetafieldsRequestMetafields';

export interface CreateMetafieldsRequest {
  metafields: CreateMetafieldsRequestMetafields;
}

export const createMetafieldsRequestSchema: Schema<CreateMetafieldsRequest> = object(
  {
    metafields: [
      'metafields',
      lazy(() => createMetafieldsRequestMetafieldsSchema),
    ],
  }
);
