/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { CardType1Enum, cardType1EnumSchema } from './cardType1Enum';

export interface CreditCardPaymentProfile {
  id?: number;
  firstName?: string;
  lastName?: string;
  maskedCardNumber?: string;
  cardType?: CardType1Enum;
  expirationMonth?: number;
  expirationYear?: number;
  customerId?: number;
  currentVault?: string;
  vaultToken?: string;
  billingAddress?: string;
  billingCity?: string;
  billingState?: string;
  billingZip?: string;
  billingCountry?: string;
  customerVaultToken?: string | null;
  billingAddress2?: string;
  paymentType?: string;
  disabled?: boolean;
  siteGatewaySettingId?: string;
  gatewayHandle?: string | null;
}

export const creditCardPaymentProfileSchema: Schema<CreditCardPaymentProfile> = object(
  {
    id: ['id', optional(number())],
    firstName: ['first_name', optional(string())],
    lastName: ['last_name', optional(string())],
    maskedCardNumber: ['masked_card_number', optional(string())],
    cardType: ['card_type', optional(cardType1EnumSchema)],
    expirationMonth: ['expiration_month', optional(number())],
    expirationYear: ['expiration_year', optional(number())],
    customerId: ['customer_id', optional(number())],
    currentVault: ['current_vault', optional(string())],
    vaultToken: ['vault_token', optional(string())],
    billingAddress: ['billing_address', optional(string())],
    billingCity: ['billing_city', optional(string())],
    billingState: ['billing_state', optional(string())],
    billingZip: ['billing_zip', optional(string())],
    billingCountry: ['billing_country', optional(string())],
    customerVaultToken: ['customer_vault_token', optional(nullable(string()))],
    billingAddress2: ['billing_address_2', optional(string())],
    paymentType: ['payment_type', optional(string())],
    disabled: ['disabled', optional(boolean())],
    siteGatewaySettingId: ['site_gateway_setting_id', optional(string())],
    gatewayHandle: ['gateway_handle', optional(nullable(string()))],
  }
);
