/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CreditTypeEnum
 */
export enum CreditTypeEnum {
  Full = 'full',
  Prorated = 'prorated',
  None = 'none',
}

/**
 * Schema for CreditTypeEnum
 */
export const creditTypeEnumSchema: Schema<CreditTypeEnum> = stringEnum(CreditTypeEnum);
