/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CreditType1Enum
 */
export enum CreditType1Enum {
  Full = 'full',
  Prorated = 'prorated',
  None = 'none',
}

/**
 * Schema for CreditType1Enum
 */
export const creditType1EnumSchema: Schema<CreditType1Enum> = stringEnum(CreditType1Enum);
