/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema } from '../schema';
import { CreditSchemeEnum, creditSchemeEnumSchema } from './creditSchemeEnum';

export interface CreditSchemeRequest {
  creditScheme: CreditSchemeEnum;
}

export const creditSchemeRequestSchema: Schema<CreditSchemeRequest> = object({
  creditScheme: ['credit_scheme', creditSchemeEnumSchema],
});
