/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CreditSchemeEnum
 */
export enum CreditSchemeEnum {
  None = 'none',
  Credit = 'credit',
  Refund = 'refund',
}

/**
 * Schema for CreditSchemeEnum
 */
export const creditSchemeEnumSchema: Schema<CreditSchemeEnum> = stringEnum(CreditSchemeEnum);
