/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CurrentVaultEnum
 */
export enum CurrentVaultEnum {
  Authorizenet = 'authorizenet',
  TrustCommerce = 'trust_commerce',
  PaymentExpress = 'payment_express',
  Beanstream = 'beanstream',
  BraintreeBlue = 'braintree_blue',
  Paypal = 'paypal',
  Eway = 'eway',
  EwayRapidStd = 'eway_rapid_std',
  StripeConnect = 'stripe_connect',
  Pin = 'pin',
  Wirecard = 'wirecard',
  Bpoint = 'bpoint',
  Firstdata = 'firstdata',
  Elavon = 'elavon',
  Cybersource = 'cybersource',
  Paymill = 'paymill',
  Moneris = 'moneris',
  Litle = 'litle',
  Square = 'square',
}

/**
 * Schema for CurrentVaultEnum
 */
export const currentVaultEnumSchema: Schema<CurrentVaultEnum> = stringEnum(CurrentVaultEnum);
