/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import {
  DeductServiceCreditAmount,
  deductServiceCreditAmountSchema,
} from './containers/deductServiceCreditAmount';

export interface DeductServiceCredit {
  amount: DeductServiceCreditAmount;
  memo: string;
}

export const deductServiceCreditSchema: Schema<DeductServiceCredit> = object({
  amount: ['amount', optional(deductServiceCreditAmountSchema)],
  memo: ['memo', string()],
});
