/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for DirectionEnum
 */
export enum DirectionEnum {
  Asc = 'asc',
  Desc = 'desc',
}

/**
 * Schema for DirectionEnum
 */
export const directionEnumSchema: Schema<DirectionEnum> = stringEnum(DirectionEnum);
