/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for DiscountTypeEnum
 */
export enum DiscountTypeEnum {
  Amount = 'amount',
  Percent = 'percent',
}

/**
 * Schema for DiscountTypeEnum
 */
export const discountTypeEnumSchema: Schema<DiscountTypeEnum> = stringEnum(DiscountTypeEnum);
