/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Refund1, refund1Schema } from './refund1';

export interface Errors15 {
  refund?: Refund1;
}

export const errors15Schema: Schema<Errors15> = object({
  refund: ['refund', optional(lazy(() => refund1Schema))],
});
