/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface Errors3 {
  kind?: string;
  componentId?: number;
  on?: string;
  message?: string;
}

export const errors3Schema: Schema<Errors3> = object({
  kind: ['kind', optional(string())],
  componentId: ['component_id', optional(number())],
  on: ['on', optional(string())],
  message: ['message', optional(string())],
});
