/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Refund2, refund2Schema } from './refund2';

export interface Errors16 {
  refund?: Refund2;
}

export const errors16Schema: Schema<Errors16> = object({
  refund: ['refund', optional(lazy(() => refund2Schema))],
});
