/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Member, memberSchema } from './member';

export interface Errors8 {
  members?: Member[];
}

export const errors8Schema: Schema<Errors8> = object({
  members: ['members', optional(array(lazy(() => memberSchema)))],
});
