/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema, unknown } from '../schema';

export interface Errors14 {
  attribute: unknown[];
}

export const errors14Schema: Schema<Errors14> = object({
  attribute: ['attribute', array(unknown())],
});
