/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Errors4 {
  kind?: string;
  message?: string;
}

export const errors4Schema: Schema<Errors4> = object({
  kind: ['kind', optional(string())],
  message: ['message', optional(string())],
});
