/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Segments, segmentsSchema } from './segments';

export interface Errors12 {
  segments: Segments;
}

export const errors12Schema: Schema<Errors12> = object({
  segments: ['segments', lazy(() => segmentsSchema)],
});
