/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';

export interface Errors9 {
  base?: string[];
  pricingScheme?: string[];
  prices?: string[];
  propertyValuesFingerprint?: string[];
}

export const errors9Schema: Schema<Errors9> = object({
  base: ['base', optional(array(string()))],
  pricingScheme: ['pricing_scheme', optional(array(string()))],
  prices: ['prices', optional(array(string()))],
  propertyValuesFingerprint: [
    'property_values_fingerprint',
    optional(array(string())),
  ],
});
