/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface Errors2 {
  componentId?: number;
  pricePoint?: number;
  message?: string;
}

export const errors2Schema: Schema<Errors2> = object({
  componentId: ['component_id', optional(number())],
  pricePoint: ['price_point', optional(number())],
  message: ['message', optional(string())],
});
