/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';

export interface Errors6 {
  components?: string[];
}

export const errors6Schema: Schema<Errors6> = object({
  components: ['components', optional(array(string()))],
});
