/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, unknown } from '../schema';

export interface Errors7 {
  customer?: unknown;
  paymentProfile?: unknown;
  subscriptions?: unknown;
}

export const errors7Schema: Schema<Errors7> = object({
  customer: ['customer', optional(unknown())],
  paymentProfile: ['payment_profile', optional(unknown())],
  subscriptions: ['subscriptions', optional(unknown())],
});
