/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Subscription1, subscription1Schema } from './subscription1';

export interface Errors18 {
  subscription?: Subscription1;
}

export const errors18Schema: Schema<Errors18> = object({
  subscription: ['subscription', optional(lazy(() => subscription1Schema))],
});
