/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';

export interface Errors10 {
  perPage?: string[];
  pricePoint?: string[];
}

export const errors10Schema: Schema<Errors10> = object({
  perPage: ['per_page', optional(array(string()))],
  pricePoint: ['price_point', optional(array(string()))],
});
