/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface EventData {
  previousSubscriptionState: string;
  newSubscriptionState: string;
}

export const eventDataSchema: Schema<EventData> = object({
  previousSubscriptionState: ['previous_subscription_state', string()],
  newSubscriptionState: ['new_subscription_state', string()],
});
