/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ExtendedIntervalUnitEnum
 */
export enum ExtendedIntervalUnitEnum {
  Day = 'day',
  Month = 'month',
  Never = 'never',
}

/**
 * Schema for ExtendedIntervalUnitEnum
 */
export const extendedIntervalUnitEnumSchema: Schema<ExtendedIntervalUnitEnum> = stringEnum(ExtendedIntervalUnitEnum);
