/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for FailedPaymentActionEnum
 */
export enum FailedPaymentActionEnum {
  LeaveOpenInvoice = 'leave_open_invoice',
  RollbackToPending = 'rollback_to_pending',
  InitiateDunning = 'initiate_dunning',
}

/**
 * Schema for FailedPaymentActionEnum
 */
export const failedPaymentActionEnumSchema: Schema<FailedPaymentActionEnum> = stringEnum(FailedPaymentActionEnum);
