/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for FirstChargeTypeEnum
 */
export enum FirstChargeTypeEnum {
  Prorated = 'prorated',
  Immediate = 'immediate',
  Delayed = 'delayed',
}

/**
 * Schema for FirstChargeTypeEnum
 */
export const firstChargeTypeEnumSchema: Schema<FirstChargeTypeEnum> = stringEnum(FirstChargeTypeEnum);
