/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for GroupTargetTypeEnum
 */
export enum GroupTargetTypeEnum {
  Customer = 'customer',
  Subscription = 'subscription',
  Self = 'self',
  Parent = 'parent',
  Eldest = 'eldest',
}

/**
 * Schema for GroupTargetTypeEnum
 */
export const groupTargetTypeEnumSchema: Schema<GroupTargetTypeEnum> = stringEnum(GroupTargetTypeEnum);
