/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';
import {
  GroupTargetTypeEnum,
  groupTargetTypeEnumSchema,
} from './groupTargetTypeEnum';

/** Attributes of the target customer who will be the responsible payer of the created subscription. Required. */
export interface GroupTarget {
  /** The type of object indicated by the id attribute. */
  type: GroupTargetTypeEnum;
  /** The id of the target customer or subscription to group the existing subscription with. Ignored and should not be included if type is "self" , "parent", or "eldest" */
  id?: number;
}

export const groupTargetSchema: Schema<GroupTarget> = object({
  type: ['type', groupTargetTypeEnumSchema],
  id: ['id', optional(number())],
});
