/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for HolderTypeEnum
 */
export enum HolderTypeEnum {
  Personal = 'personal',
  Business = 'business',
}

/**
 * Schema for HolderTypeEnum
 */
export const holderTypeEnumSchema: Schema<HolderTypeEnum> = stringEnum(HolderTypeEnum);
