/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for IncludeNotNullEnum
 */
export enum IncludeNotNullEnum {
  NotNull = 'not_null',
}

/**
 * Schema for IncludeNotNullEnum
 */
export const includeNotNullEnumSchema: Schema<IncludeNotNullEnum> = stringEnum(IncludeNotNullEnum);
