/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for IncludeOptionEnum
 */
export enum IncludeOptionEnum {
  Exclude = '0',
  Include = '1',
}

/**
 * Schema for IncludeOptionEnum
 */
export const includeOptionEnumSchema: Schema<IncludeOptionEnum> = stringEnum(IncludeOptionEnum);
