/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for IntervalUnitEnum
 */
export enum IntervalUnitEnum {
  Day = 'day',
  Month = 'month',
}

/**
 * Schema for IntervalUnitEnum
 */
export const intervalUnitEnumSchema: Schema<IntervalUnitEnum> = stringEnum(IntervalUnitEnum);
