/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for InvoiceDateFieldEnum
 */
export enum InvoiceDateFieldEnum {
  CreatedAt = 'created_at',
  DueDate = 'due_date',
  IssueDate = 'issue_date',
  UpdatedAt = 'updated_at',
  PaidDate = 'paid_date',
}

/**
 * Schema for InvoiceDateFieldEnum
 */
export const invoiceDateFieldEnumSchema: Schema<InvoiceDateFieldEnum> = stringEnum(InvoiceDateFieldEnum);
