/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for InvoiceEventTypeEnum
 */
export enum InvoiceEventTypeEnum {
  IssueInvoice = 'issue_invoice',
  ApplyCreditNote = 'apply_credit_note',
  ApplyPayment = 'apply_payment',
  RefundInvoice = 'refund_invoice',
  VoidInvoice = 'void_invoice',
  VoidRemainder = 'void_remainder',
  BackportInvoice = 'backport_invoice',
  ChangeInvoiceStatus = 'change_invoice_status',
  ChangeInvoiceCollectionMethod = 'change_invoice_collection_method',
  RemovePayment = 'remove_payment',
}

/**
 * Schema for InvoiceEventTypeEnum
 */
export const invoiceEventTypeEnumSchema: Schema<InvoiceEventTypeEnum> = stringEnum(InvoiceEventTypeEnum);
