/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for InvoiceSortFieldEnum
 */
export enum InvoiceSortFieldEnum {
  Status = 'status',
  TotalAmount = 'total_amount',
  DueAmount = 'due_amount',
  CreatedAt = 'created_at',
  UpdatedAt = 'updated_at',
  IssueDate = 'issue_date',
  DueDate = 'due_date',
  Number = 'number',
}

/**
 * Schema for InvoiceSortFieldEnum
 */
export const invoiceSortFieldEnumSchema: Schema<InvoiceSortFieldEnum> = stringEnum(InvoiceSortFieldEnum);
