/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for InvoicePaymentTypeEnum
 */
export enum InvoicePaymentTypeEnum {
  External = 'external',
  Prepayment = 'prepayment',
  ServiceCredit = 'service_credit',
  Payment = 'payment',
}

/**
 * Schema for InvoicePaymentTypeEnum
 */
export const invoicePaymentTypeEnumSchema: Schema<InvoicePaymentTypeEnum> = stringEnum(InvoicePaymentTypeEnum);
