/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for InvoiceConsolidationLevelEnum
 */
export enum InvoiceConsolidationLevelEnum {
  None = 'none',
  Child = 'child',
  Parent = 'parent',
}

/**
 * Schema for InvoiceConsolidationLevelEnum
 */
export const invoiceConsolidationLevelEnumSchema: Schema<InvoiceConsolidationLevelEnum> = stringEnum(InvoiceConsolidationLevelEnum);
