/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for InvoicePaymentMethodTypeEnum
 */
export enum InvoicePaymentMethodTypeEnum {
  CreditCard = 'credit_card',
  Check = 'check',
  Cash = 'cash',
  MoneyOrder = 'money_order',
  Ach = 'ach',
  Other = 'other',
}

/**
 * Schema for InvoicePaymentMethodTypeEnum
 */
export const invoicePaymentMethodTypeEnumSchema: Schema<InvoicePaymentMethodTypeEnum> = stringEnum(InvoicePaymentMethodTypeEnum);
