/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import {
  IssueServiceCreditAmount,
  issueServiceCreditAmountSchema,
} from './containers/issueServiceCreditAmount';

export interface IssueServiceCredit {
  amount: IssueServiceCreditAmount;
  memo: string;
}

export const issueServiceCreditSchema: Schema<IssueServiceCredit> = object({
  amount: ['amount', optional(issueServiceCreditAmountSchema)],
  memo: ['memo', string()],
});
