/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for LegacyPaymentCollectionMethodEnum
 */
export enum LegacyPaymentCollectionMethodEnum {
  Automatic = 'automatic',
  Invoice = 'invoice',
}

/**
 * Schema for LegacyPaymentCollectionMethodEnum
 */
export const legacyPaymentCollectionMethodEnumSchema: Schema<LegacyPaymentCollectionMethodEnum> = stringEnum(LegacyPaymentCollectionMethodEnum);
