/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ListSubscriptionGroupPrepaymentDateFieldEnum
 */
export enum ListSubscriptionGroupPrepaymentDateFieldEnum {
  CreatedAt = 'created_at',
  ApplicationAt = 'application_at',
}

/**
 * Schema for ListSubscriptionGroupPrepaymentDateFieldEnum
 */
export const listSubscriptionGroupPrepaymentDateFieldEnumSchema: Schema<ListSubscriptionGroupPrepaymentDateFieldEnum> = stringEnum(ListSubscriptionGroupPrepaymentDateFieldEnum);
