/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ListSubscriptionComponentsSortEnum
 */
export enum ListSubscriptionComponentsSortEnum {
  Id = 'id',
  UpdatedAt = 'updated_at',
}

/**
 * Schema for ListSubscriptionComponentsSortEnum
 */
export const listSubscriptionComponentsSortEnumSchema: Schema<ListSubscriptionComponentsSortEnum> = stringEnum(ListSubscriptionComponentsSortEnum);
