/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ListComponentsPricePointsIncludeEnum
 */
export enum ListComponentsPricePointsIncludeEnum {
  CurrencyPrices = 'currency_prices',
}

/**
 * Schema for ListComponentsPricePointsIncludeEnum
 */
export const listComponentsPricePointsIncludeEnumSchema: Schema<ListComponentsPricePointsIncludeEnum> = stringEnum(ListComponentsPricePointsIncludeEnum);
