/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ListSubscriptionComponentsSubscriptionDateFieldEnum
 */
export enum ListSubscriptionComponentsSubscriptionDateFieldEnum {
  UpdatedAt = 'updated_at',
}

/**
 * Schema for ListSubscriptionComponentsSubscriptionDateFieldEnum
 */
export const listSubscriptionComponentsSubscriptionDateFieldEnumSchema: Schema<ListSubscriptionComponentsSubscriptionDateFieldEnum> = stringEnum(ListSubscriptionComponentsSubscriptionDateFieldEnum);
