/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ListSubscriptionComponentsIncludeEnum
 */
export enum ListSubscriptionComponentsIncludeEnum {
  Subscription = 'subscription',
}

/**
 * Schema for ListSubscriptionComponentsIncludeEnum
 */
export const listSubscriptionComponentsIncludeEnumSchema: Schema<ListSubscriptionComponentsIncludeEnum> = stringEnum(ListSubscriptionComponentsIncludeEnum);
