/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import {
  ComponentPricePointResponse,
  componentPricePointResponseSchema,
} from './componentPricePointResponse';

export interface ListComponentsPricePointsResponse {
  pricePoints: ComponentPricePointResponse[];
}

export const listComponentsPricePointsResponseSchema: Schema<ListComponentsPricePointsResponse> = object(
  {
    pricePoints: [
      'price_points',
      array(lazy(() => componentPricePointResponseSchema)),
    ],
  }
);
