/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ListSubscriptionComponentsDateFieldEnum
 */
export enum ListSubscriptionComponentsDateFieldEnum {
  UpdatedAt = 'updated_at',
}

/**
 * Schema for ListSubscriptionComponentsDateFieldEnum
 */
export const listSubscriptionComponentsDateFieldEnumSchema: Schema<ListSubscriptionComponentsDateFieldEnum> = stringEnum(ListSubscriptionComponentsDateFieldEnum);
