/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ListProductsPricePointsIncludeEnum
 */
export enum ListProductsPricePointsIncludeEnum {
  CurrencyPrices = 'currency_prices',
}

/**
 * Schema for ListProductsPricePointsIncludeEnum
 */
export const listProductsPricePointsIncludeEnumSchema: Schema<ListProductsPricePointsIncludeEnum> = stringEnum(ListProductsPricePointsIncludeEnum);
