/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ListEventsDateFieldEnum
 */
export enum ListEventsDateFieldEnum {
  CreatedAt = 'created_at',
}

/**
 * Schema for ListEventsDateFieldEnum
 */
export const listEventsDateFieldEnumSchema: Schema<ListEventsDateFieldEnum> = stringEnum(ListEventsDateFieldEnum);
