/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ListProductsIncludeEnum
 */
export enum ListProductsIncludeEnum {
  PrepaidProductPricePoint = 'prepaid_product_price_point',
}

/**
 * Schema for ListProductsIncludeEnum
 */
export const listProductsIncludeEnumSchema: Schema<ListProductsIncludeEnum> = stringEnum(ListProductsIncludeEnum);
