/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface Member {
  id?: number;
  type?: string;
  message?: string;
}

export const memberSchema: Schema<Member> = object({
  id: ['id', optional(number())],
  type: ['type', optional(string())],
  message: ['message', optional(string())],
});
