/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for MetafieldInputEnum
 */
export enum MetafieldInputEnum {
  Text = 'text',
  Radio = 'radio',
  Dropdown = 'dropdown',
}

/**
 * Schema for MetafieldInputEnum
 */
export const metafieldInputEnumSchema: Schema<MetafieldInputEnum> = stringEnum(MetafieldInputEnum);
