/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface MRRMovement {
  amount?: number;
  category?: string;
}

export const mRRMovementSchema: Schema<MRRMovement> = object({
  amount: ['amount', optional(number())],
  category: ['category', optional(string())],
});
