/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  number,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';

export interface OfferItem {
  componentId?: number;
  pricePointId?: number;
  startingQuantity?: string;
  editable?: boolean;
  componentUnitPrice?: string;
  componentName?: string;
  pricePointName?: string;
  currencyPrices?: unknown[];
}

export const offerItemSchema: Schema<OfferItem> = object({
  componentId: ['component_id', optional(number())],
  pricePointId: ['price_point_id', optional(number())],
  startingQuantity: ['starting_quantity', optional(string())],
  editable: ['editable', optional(boolean())],
  componentUnitPrice: ['component_unit_price', optional(string())],
  componentName: ['component_name', optional(string())],
  pricePointName: ['price_point_name', optional(string())],
  currencyPrices: ['currency_prices', optional(array(unknown()))],
});
