/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import {
  OveragePricingPrices,
  overagePricingPricesSchema,
} from './containers/overagePricingPrices';
import {
  OveragePricingPricingScheme,
  overagePricingPricingSchemeSchema,
} from './containers/overagePricingPricingScheme';

export interface OveragePricing {
  /** The identifier for the pricing scheme. See [Product Components](https://help.chargify.com/products/product-components.html) for an overview of pricing schemes. */
  pricingScheme: OveragePricingPricingScheme;
  prices?: OveragePricingPrices[];
}

export const overagePricingSchema: Schema<OveragePricing> = object({
  pricingScheme: ['pricing_scheme', overagePricingPricingSchemeSchema],
  prices: ['prices', optional(array(lazy(() => overagePricingPricesSchema)))],
});
