/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { StatusEnum, statusEnumSchema } from './statusEnum';

export interface Payment {
  /** The uid of the paid invoice */
  invoiceUid?: string;
  /** The current status of the invoice. See [Invoice Statuses](https://chargify.zendesk.com/hc/en-us/articles/4407737494171#line-item-breakdowns) for more. */
  status?: StatusEnum;
  /** The remaining due amount on the invoice */
  dueAmount?: string;
  /** The total amount paid on this invoice (including any prior payments) */
  paidAmount?: string;
}

export const paymentSchema: Schema<Payment> = object({
  invoiceUid: ['invoice_uid', optional(string())],
  status: ['status', optional(statusEnumSchema)],
  dueAmount: ['due_amount', optional(string())],
  paidAmount: ['paid_amount', optional(string())],
});
