/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PaymentProfileVaultEnum
 */
export enum PaymentProfileVaultEnum {
  Bogus = 'bogus',
  Authorizenet = 'authorizenet',
  TrustCommerce = 'trust_commerce',
  PaymentExpress = 'payment_express',
  Beanstream = 'beanstream',
  BraintreeBlue = 'braintree_blue',
  Paypal = 'paypal',
  Quickpay = 'quickpay',
  Eway = 'eway',
  Stripe = 'stripe',
  Wirecard = 'wirecard',
}

/**
 * Schema for PaymentProfileVaultEnum
 */
export const paymentProfileVaultEnumSchema: Schema<PaymentProfileVaultEnum> = stringEnum(PaymentProfileVaultEnum);
