/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PaymentCollectionMethodForSubscriptionEnum
 */
export enum PaymentCollectionMethodForSubscriptionEnum {
  Automatic = 'automatic',
  Remittance = 'remittance',
  Prepaid = 'prepaid',
  Invoice = 'invoice',
}

/**
 * Schema for PaymentCollectionMethodForSubscriptionEnum
 */
export const paymentCollectionMethodForSubscriptionEnumSchema: Schema<PaymentCollectionMethodForSubscriptionEnum> = stringEnum(PaymentCollectionMethodForSubscriptionEnum);
