/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PaymentTypeEnum
 */
export enum PaymentTypeEnum {
  CreditCard = 'credit_card',
  BankAccount = 'bank_account',
  PaypalAccount = 'paypal_account',
}

/**
 * Schema for PaymentTypeEnum
 */
export const paymentTypeEnumSchema: Schema<PaymentTypeEnum> = stringEnum(PaymentTypeEnum);
