/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, number, object, optional, Schema, string } from '../schema';

export interface Payment1 {
  id?: number;
  amountInCents?: number;
  success?: boolean;
  memo?: string;
}

export const payment1Schema: Schema<Payment1> = object({
  id: ['id', optional(number())],
  amountInCents: ['amount_in_cents', optional(number())],
  success: ['success', optional(boolean())],
  memo: ['memo', optional(string())],
});
