/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import {
  CreateComponentPrice,
  createComponentPriceSchema,
} from './createComponentPrice';
import { OveragePricing, overagePricingSchema } from './overagePricing';

export interface PrepaidComponentPricePoint {
  name?: string;
  handle?: string;
  pricingScheme?: string;
  prices?: CreateComponentPrice[];
  overagePricing?: OveragePricing;
}

export const prepaidComponentPricePointSchema: Schema<PrepaidComponentPricePoint> = object(
  {
    name: ['name', optional(string())],
    handle: ['handle', optional(string())],
    pricingScheme: ['pricing_scheme', optional(string())],
    prices: ['prices', optional(array(lazy(() => createComponentPriceSchema)))],
    overagePricing: [
      'overage_pricing',
      optional(lazy(() => overagePricingSchema)),
    ],
  }
);
