/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  number,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';

export interface Prepayment1 {
  id: number;
  subscriptionId: number;
  amountInCents: number;
  remainingAmountInCents: number;
  details?: unknown;
  external: boolean;
  memo: string;
  paymentType?: unknown;
  createdAt: string;
}

export const prepayment1Schema: Schema<Prepayment1> = object({
  id: ['id', number()],
  subscriptionId: ['subscription_id', number()],
  amountInCents: ['amount_in_cents', number()],
  remainingAmountInCents: ['remaining_amount_in_cents', number()],
  details: ['details', optional(unknown())],
  external: ['external', boolean()],
  memo: ['memo', string()],
  paymentType: ['payment_type', optional(unknown())],
  createdAt: ['created_at', string()],
});
