/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PrepaymentMethodEnum
 */
export enum PrepaymentMethodEnum {
  Check = 'check',
  Cash = 'cash',
  MoneyOrder = 'money_order',
  Ach = 'ach',
  PaypalAccount = 'paypal_account',
  CreditCardOnFile = 'credit_card_on_file',
  Other = 'other',
}

/**
 * Schema for PrepaymentMethodEnum
 */
export const prepaymentMethodEnumSchema: Schema<PrepaymentMethodEnum> = stringEnum(PrepaymentMethodEnum);
