/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PricePointTypeEnum
 */
export enum PricePointTypeEnum {
  Catalog = 'catalog',
  Default = 'default',
  Custom = 'custom',
}

/**
 * Schema for PricePointTypeEnum
 */
export const pricePointTypeEnumSchema: Schema<PricePointTypeEnum> = stringEnum(PricePointTypeEnum);
