/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, optional, Schema } from '../schema';
import {
  PriceEndingQuantity,
  priceEndingQuantitySchema,
} from './containers/priceEndingQuantity';
import {
  PriceStartingQuantity,
  priceStartingQuantitySchema,
} from './containers/priceStartingQuantity';
import {
  PriceUnitPrice,
  priceUnitPriceSchema,
} from './containers/priceUnitPrice';

export interface Price {
  startingQuantity: PriceStartingQuantity;
  endingQuantity?: PriceEndingQuantity | null;
  unitPrice: PriceUnitPrice;
}

export const priceSchema: Schema<Price> = object({
  startingQuantity: [
    'starting_quantity',
    optional(priceStartingQuantitySchema),
  ],
  endingQuantity: [
    'ending_quantity',
    optional(nullable(priceEndingQuantitySchema)),
  ],
  unitPrice: ['unit_price', optional(priceUnitPriceSchema)],
});
