/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PricingSchemeEnum
 */
export enum PricingSchemeEnum {
  Stairstep = 'stairstep',
  Volume = 'volume',
  PerUnit = 'per_unit',
  Tiered = 'tiered',
}

/**
 * Schema for PricingSchemeEnum
 */
export const pricingSchemeEnumSchema: Schema<PricingSchemeEnum> = stringEnum(PricingSchemeEnum);
