/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';

export interface ProformaInvoiceLineItem {
  uid?: string;
  title?: string;
  description?: string;
  quantity?: string;
  unitPrice?: string;
  subtotalAmount?: string;
  discountAmount?: string;
  taxAmount?: string;
  totalAmount?: string;
  tieredUnitPrice?: boolean;
  periodRangeStart?: string;
  periodRangeEnd?: string;
  productId?: number;
  productVersion?: number;
  productPricePointId?: number;
  componentId?: string | null;
  pricePointId?: string | null;
}

export const proformaInvoiceLineItemSchema: Schema<ProformaInvoiceLineItem> = object(
  {
    uid: ['uid', optional(string())],
    title: ['title', optional(string())],
    description: ['description', optional(string())],
    quantity: ['quantity', optional(string())],
    unitPrice: ['unit_price', optional(string())],
    subtotalAmount: ['subtotal_amount', optional(string())],
    discountAmount: ['discount_amount', optional(string())],
    taxAmount: ['tax_amount', optional(string())],
    totalAmount: ['total_amount', optional(string())],
    tieredUnitPrice: ['tiered_unit_price', optional(boolean())],
    periodRangeStart: ['period_range_start', optional(string())],
    periodRangeEnd: ['period_range_end', optional(string())],
    productId: ['product_id', optional(number())],
    productVersion: ['product_version', optional(number())],
    productPricePointId: ['product_price_point_id', optional(number())],
    componentId: ['component_id', optional(nullable(string()))],
    pricePointId: ['price_point_id', optional(nullable(string()))],
  }
);
