/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, number, object, optional, Schema, string } from '../schema';

export interface ProformaCustomer {
  chargifyId?: number;
  firstName?: string;
  lastName?: string;
  organization?: string;
  email?: string;
  vatNumber?: string | null;
  reference?: string | null;
}

export const proformaCustomerSchema: Schema<ProformaCustomer> = object({
  chargifyId: ['chargify_id', optional(number())],
  firstName: ['first_name', optional(string())],
  lastName: ['last_name', optional(string())],
  organization: ['organization', optional(string())],
  email: ['email', optional(string())],
  vatNumber: ['vat_number', optional(nullable(string()))],
  reference: ['reference', optional(nullable(string()))],
});
