/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ReactivationChargeEnum
 */
export enum ReactivationChargeEnum {
  Prorated = 'prorated',
  Immediate = 'immediate',
  Delayed = 'delayed',
}

/**
 * Schema for ReactivationChargeEnum
 */
export const reactivationChargeEnumSchema: Schema<ReactivationChargeEnum> = stringEnum(ReactivationChargeEnum);
