/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  ReadPaymentProfileResponsePaymentProfile,
  readPaymentProfileResponsePaymentProfileSchema,
} from './containers/readPaymentProfileResponsePaymentProfile';

export interface ReadPaymentProfileResponse {
  paymentProfile: ReadPaymentProfileResponsePaymentProfile;
}

export const readPaymentProfileResponseSchema: Schema<ReadPaymentProfileResponse> = object(
  {
    paymentProfile: [
      'payment_profile',
      optional(readPaymentProfileResponsePaymentProfileSchema),
    ],
  }
);
