/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for RecurringSchemeEnum
 */
export enum RecurringSchemeEnum {
  DoNotRecur = 'do_not_recur',
  RecurIndefinitely = 'recur_indefinitely',
}

/**
 * Schema for RecurringSchemeEnum
 */
export const recurringSchemeEnumSchema: Schema<RecurringSchemeEnum> = stringEnum(RecurringSchemeEnum);
