/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';

export interface Refund2 {
  amountInCents?: string[];
  base?: string[];
  external?: string[];
}

export const refund2Schema: Schema<Refund2> = object({
  amountInCents: ['amount_in_cents', optional(array(string()))],
  base: ['base', optional(array(string()))],
  external: ['external', optional(array(string()))],
});
