/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ResourceTypeEnum
 */
export enum ResourceTypeEnum {
  Subscriptions = 'subscriptions',
  Customers = 'customers',
}

/**
 * Schema for ResourceTypeEnum
 */
export const resourceTypeEnumSchema: Schema<ResourceTypeEnum> = stringEnum(ResourceTypeEnum);
