/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for RestrictionTypeEnum
 */
export enum RestrictionTypeEnum {
  Component = 'Component',
  Product = 'Product',
}

/**
 * Schema for RestrictionTypeEnum
 */
export const restrictionTypeEnumSchema: Schema<RestrictionTypeEnum> = stringEnum(RestrictionTypeEnum);
