/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ResumptionChargeEnum
 */
export enum ResumptionChargeEnum {
  Prorated = 'prorated',
  Immediate = 'immediate',
  Delayed = 'delayed',
}

/**
 * Schema for ResumptionChargeEnum
 */
export const resumptionChargeEnumSchema: Schema<ResumptionChargeEnum> = stringEnum(ResumptionChargeEnum);
