/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { X1, x1Schema } from './x1';

export interface Segments1 {
  /**
   * An attribute 'x' would be changed for a number (an index in request array) where the error occured.
   * In this object, the key represents the field and the value is an array with error messages. In most cases this object would contain just one key.
   */
  x?: X1;
}

export const segments1Schema: Schema<Segments1> = object({
  x: [''x'', optional(lazy(() => x1Schema))],
});
