/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { X, xSchema } from './x';

export interface Segments {
  /**
   * An attribute 'x' would be changed for a number (an index in request array) where the error occured.
   * In this object, the key represents the field and the value is an array with error messages. In most cases this object would contain just one key.
   */
  x?: X;
}

export const segmentsSchema: Schema<Segments> = object({
  x: [''x'', optional(lazy(() => xSchema))],
});
