/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ServiceCreditTypeEnum
 */
export enum ServiceCreditTypeEnum {
  Credit = 'Credit',
  Debit = 'Debit',
}

/**
 * Schema for ServiceCreditTypeEnum
 */
export const serviceCreditTypeEnumSchema: Schema<ServiceCreditTypeEnum> = stringEnum(ServiceCreditTypeEnum);
