/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, unknown } from '../schema';

export interface SignupProformaPreview {
  currentProformaInvoice?: unknown;
  nextProformaInvoice?: unknown;
}

export const signupProformaPreviewSchema: Schema<SignupProformaPreview> = object(
  {
    currentProformaInvoice: ['current_proforma_invoice', optional(unknown())],
    nextProformaInvoice: ['next_proforma_invoice', optional(unknown())],
  }
);
