/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for SortingDirectionEnum
 */
export enum SortingDirectionEnum {
  Asc = 'asc',
  Desc = 'desc',
}

/**
 * Schema for SortingDirectionEnum
 */
export const sortingDirectionEnumSchema: Schema<SortingDirectionEnum> = stringEnum(SortingDirectionEnum);
