/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for SubscriptionIncludeEnum
 */
export enum SubscriptionIncludeEnum {
  Coupons = 'coupons',
  SelfServicePageToken = 'self_service_page_token',
}

/**
 * Schema for SubscriptionIncludeEnum
 */
export const subscriptionIncludeEnumSchema: Schema<SubscriptionIncludeEnum> = stringEnum(SubscriptionIncludeEnum);
