/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  SignupCollectionMethodEnum,
  signupCollectionMethodEnumSchema,
} from './signupCollectionMethodEnum';
import {
  SubscriptionGroupItem,
  subscriptionGroupItemSchema,
} from './subscriptionGroupItem';

export interface SubscriptionGroupSignupResponse {
  uid?: string;
  scheme?: number;
  customerId?: number;
  paymentProfileId?: number;
  subscriptionIds?: number[];
  primarySubscriptionId?: number;
  nextAssessmentAt?: string;
  state?: string;
  cancelAtEndOfPeriod?: boolean;
  subscriptions?: SubscriptionGroupItem[];
  paymentCollectionMethod?: SignupCollectionMethodEnum;
}

export const subscriptionGroupSignupResponseSchema: Schema<SubscriptionGroupSignupResponse> = object(
  {
    uid: ['uid', optional(string())],
    scheme: ['scheme', optional(number())],
    customerId: ['customer_id', optional(number())],
    paymentProfileId: ['payment_profile_id', optional(number())],
    subscriptionIds: ['subscription_ids', optional(array(number()))],
    primarySubscriptionId: ['primary_subscription_id', optional(number())],
    nextAssessmentAt: ['next_assessment_at', optional(string())],
    state: ['state', optional(string())],
    cancelAtEndOfPeriod: ['cancel_at_end_of_period', optional(boolean())],
    subscriptions: [
      'subscriptions',
      optional(array(lazy(() => subscriptionGroupItemSchema))),
    ],
    paymentCollectionMethod: [
      'payment_collection_method',
      optional(signupCollectionMethodEnumSchema),
    ],
  }
);
