/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import {
  PrepaymentResponse,
  prepaymentResponseSchema,
} from './prepaymentResponse';

export interface SubscriptionsPrepaymentsJsonResponse {
  prepayments?: PrepaymentResponse[];
}

export const subscriptionsPrepaymentsJsonResponseSchema: Schema<SubscriptionsPrepaymentsJsonResponse> = object(
  {
    prepayments: [
      'prepayments',
      optional(array(lazy(() => prepaymentResponseSchema))),
    ],
  }
);
