/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for SubscriptionDateFieldEnum
 */
export enum SubscriptionDateFieldEnum {
  CurrentPeriodEndsAt = 'current_period_ends_at',
  CurrentPeriodStartsAt = 'current_period_starts_at',
  CreatedAt = 'created_at',
  ActivatedAt = 'activated_at',
  CanceledAt = 'canceled_at',
  ExpiresAt = 'expires_at',
  TrialStartedAt = 'trial_started_at',
  TrialEndedAt = 'trial_ended_at',
  UpdatedAt = 'updated_at',
}

/**
 * Schema for SubscriptionDateFieldEnum
 */
export const subscriptionDateFieldEnumSchema: Schema<SubscriptionDateFieldEnum> = stringEnum(SubscriptionDateFieldEnum);
