/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for SubscriptionSortEnum
 */
export enum SubscriptionSortEnum {
  SignupDate = 'signup_date',
  PeriodStart = 'period_start',
  PeriodEnd = 'period_end',
  NextAssessment = 'next_assessment',
  UpdatedAt = 'updated_at',
  CreatedAt = 'created_at',
}

/**
 * Schema for SubscriptionSortEnum
 */
export const subscriptionSortEnumSchema: Schema<SubscriptionSortEnum> = stringEnum(SubscriptionSortEnum);
