/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for SubscriptionGroupPrepaymentMethodEnum
 */
export enum SubscriptionGroupPrepaymentMethodEnum {
  Check = 'check',
  Cash = 'cash',
  MoneyOrder = 'money_order',
  Ach = 'ach',
  PaypalAccount = 'paypal_account',
  Other = 'other',
}

/**
 * Schema for SubscriptionGroupPrepaymentMethodEnum
 */
export const subscriptionGroupPrepaymentMethodEnumSchema: Schema<SubscriptionGroupPrepaymentMethodEnum> = stringEnum(SubscriptionGroupPrepaymentMethodEnum);
