/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';
import {
  SubscriptionGroupPrepaymentMethodEnum,
  subscriptionGroupPrepaymentMethodEnumSchema,
} from './subscriptionGroupPrepaymentMethodEnum';

export interface SubscriptionGroupPrepayment {
  amount: number;
  details: string;
  memo: string;
  method: SubscriptionGroupPrepaymentMethodEnum;
}

export const subscriptionGroupPrepaymentSchema: Schema<SubscriptionGroupPrepayment> = object(
  {
    amount: ['amount', number()],
    details: ['details', string()],
    memo: ['memo', string()],
    method: ['method', subscriptionGroupPrepaymentMethodEnumSchema],
  }
);
