/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TaxConfigurationKindEnum
 */
export enum TaxConfigurationKindEnum {
  Custom = 'custom',
  EnumManagedAvalara = 'managed avalara',
  EnumLinkedAvalara = 'linked avalara',
  EnumDigitalRiver = 'digital river',
}

/**
 * Schema for TaxConfigurationKindEnum
 */
export const taxConfigurationKindEnumSchema: Schema<TaxConfigurationKindEnum> = stringEnum(TaxConfigurationKindEnum);
