/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema';
import {
  TaxConfigurationKindEnum,
  taxConfigurationKindEnumSchema,
} from './taxConfigurationKindEnum';
import {
  TaxDestinationAddressEnum,
  taxDestinationAddressEnumSchema,
} from './taxDestinationAddressEnum';

export interface TaxConfiguration {
  kind?: TaxConfigurationKindEnum;
  destinationAddress?: TaxDestinationAddressEnum;
  /** Returns `true` when Chargify has been properly configured to charge tax using the specified tax system. More details about taxes: https://maxio-chargify.zendesk.com/hc/en-us/articles/5405488905869-Taxes-Introduction */
  fullyConfigured?: boolean;
}

export const taxConfigurationSchema: Schema<TaxConfiguration> = object({
  kind: ['kind', optional(taxConfigurationKindEnumSchema)],
  destinationAddress: [
    'destination_address',
    optional(taxDestinationAddressEnumSchema),
  ],
  fullyConfigured: ['fully_configured', optional(boolean())],
});
