/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TaxDestinationAddressEnum
 */
export enum TaxDestinationAddressEnum {
  ShippingThenBilling = 'shipping_then_billing',
  BillingThenShipping = 'billing_then_shipping',
  ShippingOnly = 'shipping_only',
  BillingOnly = 'billing_only',
}

/**
 * Schema for TaxDestinationAddressEnum
 */
export const taxDestinationAddressEnumSchema: Schema<TaxDestinationAddressEnum> = stringEnum(TaxDestinationAddressEnum);
