/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, optional, Schema, string } from '../schema';

export interface UpdatePaymentProfile {
  firstName?: string;
  lastName?: string;
  fullNumber?: string;
  cardType?: string;
  expirationMonth?: string;
  expirationYear?: string;
  currentVault?: string;
  billingAddress?: string;
  billingCity?: string;
  billingState?: string;
  billingZip?: string;
  billingCountry?: string;
  billingAddress2?: string | null;
}

export const updatePaymentProfileSchema: Schema<UpdatePaymentProfile> = object({
  firstName: ['first_name', optional(string())],
  lastName: ['last_name', optional(string())],
  fullNumber: ['full_number', optional(string())],
  cardType: ['card_type', optional(string())],
  expirationMonth: ['expiration_month', optional(string())],
  expirationYear: ['expiration_year', optional(string())],
  currentVault: ['current_vault', optional(string())],
  billingAddress: ['billing_address', optional(string())],
  billingCity: ['billing_city', optional(string())],
  billingState: ['billing_state', optional(string())],
  billingZip: ['billing_zip', optional(string())],
  billingCountry: ['billing_country', optional(string())],
  billingAddress2: ['billing_address_2', optional(nullable(string()))],
});
