/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema, string } from '../schema';
import {
  WebhookSubscriptionEnum,
  webhookSubscriptionEnumSchema,
} from './webhookSubscriptionEnum';

/** Used to Create or Update Endpoint */
export interface UpdateEndpoint {
  url: string;
  webhookSubscriptions: WebhookSubscriptionEnum[];
}

export const updateEndpointSchema: Schema<UpdateEndpoint> = object({
  url: ['url', string()],
  webhookSubscriptions: [
    'webhook_subscriptions',
    array(webhookSubscriptionEnumSchema),
  ],
});
