/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for WebhookOrderEnum
 */
export enum WebhookOrderEnum {
  NewestFirst = 'newest_first',
  OldestFirst = 'oldest_first',
}

/**
 * Schema for WebhookOrderEnum
 */
export const webhookOrderEnumSchema: Schema<WebhookOrderEnum> = stringEnum(WebhookOrderEnum);
