/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for WebhookStatusEnum
 */
export enum WebhookStatusEnum {
  Successful = 'successful',
  Failed = 'failed',
  Pending = 'pending',
  Paused = 'paused',
}

/**
 * Schema for WebhookStatusEnum
 */
export const webhookStatusEnumSchema: Schema<WebhookStatusEnum> = stringEnum(WebhookStatusEnum);
