/**
 * Maxio Advanced Billing formerly Chargify APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';

/**
 * An attribute 'x' would be changed for a number (an index in request array) where the error occured.
 * In this object, the key represents the field and the value is an array with error messages. In most cases this object would contain just one key.
 */
export interface X {
  base?: string[];
  pricingScheme?: string[];
  prices?: string[];
  propertyValuesFingerprint?: string[];
}

export const xSchema: Schema<X> = object({
  base: ['base', optional(array(string()))],
  pricingScheme: ['pricing_scheme', optional(array(string()))],
  prices: ['prices', optional(array(string()))],
  propertyValuesFingerprint: [
    'property_values_fingerprint',
    optional(array(string())),
  ],
});
